POST https://api.cognitive.microsofttranslator.com/translate?api-version=3.0&from=en&to=it
Content-Type: application/json
Ocp-Apim-Subscription-Key: 9NdxzsepUoIlROhrbc1aO7pc6kOzDDpjYfRMMU3pX8tqMaDErcmGJQQJ99BHAC5RqLJXJ3w3AAAbACOG3dGK
Ocp-Apim-Subscription-Region: westeurope

[
    {
        "Text": "I like to learn new languages"
    }
]
